[package]
name = "web-router"
version = "0.1.0"
authors = ["Markus Ast <m@rkusa.st>"]

[dependencies]
http = "0.1"
web = { path = "../../web" }
# web = { git = "https://github.com/rkusa/web-rs.git" }
router = { path = "../router" }
futures = "0.1"

[dev-dependencies]
hyper = "0.12"